#ifndef __ECTF_PARAMS__
#define __ECTF_PARAMS__
#define COMPONENT_ID 2575857440
#define COMPONENT_BOOT_MSG "C20 boot"
#define ATTESTATION_LOC "New York"
#define ATTESTATION_DATE "1/25/24"
#define ATTESTATION_CUSTOMER "Pace"
#endif
