#ifndef __ECTF_PARAMS__
#define __ECTF_PARAMS__
#define COMPONENT_ID 2575857441
#define COMPONENT_BOOT_MSG "Component 2"
#define ATTESTATION_LOC "PLV"
#define ATTESTATION_DATE "25/01/2024"
#define ATTESTATION_CUSTOMER "UNIVERSITY"
#endif
